output "factory_namespace" {
  value = vault_namespace.factory.path
}

output "factory_api_role_id" {
  value = vault_approle_auth_backend_role.factory_api.role_id
}

output "factory_api_secret_id_instructions" {
  value = <<-EOT
    role_id is not sensitive and is output above.
    secret_id is NEVER generated by Terraform (it must not live in state).
    Generate one out-of-band once, then set it in .env as
    FACTORY_VAULT_SECRET_ID:

      VAULT_TOKEN=<root or sufficiently-privileged token> \
      VAULT_ADDR=https://127.0.0.1:18200 \
      VAULT_NAMESPACE=factory \
      vault write -f auth/approle/role/factory-api/secret-id
  EOT
}
